const withMT = require("@material-tailwind/react/utils/withMT");

module.exports = withMT({
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/@material-tailwind/react/components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@material-tailwind/react/theme/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Roboto",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
      },
      borderRadius: {
        sm: "calc(0.625rem - 4px)",
        md: "calc(0.625rem - 2px)",
        lg: "0.625rem",
        xl: "calc(0.625rem + 4px)",
      },
      colors: {
        light: {
          background: "#ffffff",
          foreground: "#333333",
          card: "#ffffff",
          "card-foreground": "#333333",
          popover: "#ffffff",
          "popover-foreground": "#0a0a0a",
          primary: "#0A74DA",
          "primary-foreground": "#ffffff",
          secondary: "#555555",
          "secondary-foreground": "#ffffff",
          muted: "#ececf0",
          "muted-foreground": "#717182",
          accent: "#F4A261",
          "accent-foreground": "#ffffff",
          destructive: "#d4183d",
          "destructive-foreground": "#ffffff",
          border: "rgba(0, 0, 0, 0.1)",
          input: "transparent",
          "input-background": "#f3f3f5",
          "switch-background": "#cbced4",
          ring: "#b3b3b3",
          "chart-1": "#e8630a",
          "chart-2": "#12a083",
          "chart-3": "#1d4f7a",
          "chart-4": "#d4a800",
          "chart-5": "#c87800",
          sidebar: "#f9f9f9",
          "sidebar-foreground": "#0a0a0a",
          "sidebar-primary": "#030213",
          "sidebar-primary-foreground": "#f9f9f9",
          "sidebar-accent": "#f7f7f7",
          "sidebar-accent-foreground": "#1a1a1a",
          "sidebar-border": "#e5e5e5",
          "sidebar-ring": "#b3b3b3",
        },
        dark: {
          background: "#0f1419",
          foreground: "#e3e8ef",
          card: "#1a1f28",
          "card-foreground": "#e3e8ef",
          popover: "#1a1f28",
          "popover-foreground": "#e3e8ef",
          primary: "#0A74DA",
          "primary-foreground": "#ffffff",
          secondary: "#9ca3af",
          "secondary-foreground": "#ffffff",
          muted: "#2d3748",
          "muted-foreground": "#9ca3af",
          accent: "#F4A261",
          "accent-foreground": "#ffffff",
          destructive: "#6b2737",
          "destructive-foreground": "#e05a4e",
          border: "rgba(255, 255, 255, 0.1)",
          input: "transparent",
          "input-background": "#2d3748",
          ring: "#6b6b6b",
          "chart-1": "#3b5bdb",
          "chart-2": "#2ecc8f",
          "chart-3": "#c87800",
          "chart-4": "#9b5de5",
          "chart-5": "#e05a4e",
          sidebar: "#1a1a1a",
          "sidebar-foreground": "#f9f9f9",
          "sidebar-primary": "#3b5bdb",
          "sidebar-primary-foreground": "#f9f9f9",
          "sidebar-accent": "#2a2a2a",
          "sidebar-accent-foreground": "#f9f9f9",
          "sidebar-border": "#2a2a2a",
          "sidebar-ring": "#6b6b6b",
        },
      },
      fontWeight: {
        medium: "500",
        normal: "400",
      },
    },
  },
  plugins: [],
});
